name: Checks
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize
jobs:
  label:
    name: Ensure PR not in hold
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Check
        uses: mheap/github-action-required-labels@v3
        with:
          mode: exactly
          count: 0
          labels: "pr-hold"
          add_comment": "true"
