name: Checks
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
jobs:
  label: 
    name: Ensure PR not in hold
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: mheap/github-action-required-labels@v3
        with:
          mode: exactly
          count: 0
          labels: "pr-hold"
